name: 03 - Actions

on:
  push:
    branches: "feature/**"

jobs:
  checkout_java_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Pull Request para develop
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Build realizado na branch ${{ github.ref_name }} e pronto para merge"
          branch: "${{ github.ref_name }}"
          base: develop
          title: "Build pronto para merge na develop"
          body: |
            Este PR foi criado automaticamente após a conclusão bem-sucedida do build.