name: 03 - Actions

on:
  push:
    branches: "feature/**"

jobs:
  checkout_java_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Atualizar develop
        run: git checkout develop && git pull

      - name: Voltar para a branch atual
        run: git checkout ${{ github.ref_name }}

      - name: Pull Request para develop
        run: gh pr create -B ${{ github.ref_name }} -H develop --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}